spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/benchmark?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/benchmark}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
